name: cd
on:
    workflow_run:
        workflows: ['main']
        types: [completed]
    push:
    pull_request:
        branches:
            - develop
            - staging
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Docker Server build and push
                uses: docker/build-push-action@v6
                with:
                    context: ./server
                    push: true
                    tags: esbanana/yearn2learn:server
            -
                name: Docker client build and push
                uses: docker/build-push-action@v6
                with:
                    context: ./client
                    push: true
                    tags: esbanana/yearn2learn:client
                