name: cd
on:
    workflow_run:
        workflows: ['main']
        types: [completed]
    push:
    pull_request:
        branches:
            - develop
            - staging
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - 
                name: Check out the repo
                uses: actions/checkout@v2
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Docker Server build
               
                run: |
                    docker build ./server  -t esbanana/yearn2learn:server 
            -
                name: Docker Server img push
                
                run: |
                    docker push esbanana/yearn2learn:server
            -
                name: Docker Client build
                
                run: |
                    docker build ./client -t esbanana/yearn2learn:client 
            -
                name: Docker Client img push
                
                run: |
                    docker push esbanana/yearn2learn:client
